---
nginx_default_release: ""
#nginx_ppa_use: true
#nginx_ppa_version: stable
nginx_package_name: "nginx"
nginx_package_version: "1.24.0-1~{{ansible_distribution_release}}"
nginx_repo:
  - "deb https://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"
  - "deb-src https://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"

nginx_service_state: started
nginx_service_enabled: true

nginx_conf_template: "nginx.conf.j2"

nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
